### ISSUE TITLE
It works but the output is in Chinese

### ISSUE THREAD

**Issue by AddyLaddy** [manateelazycat/mind-wave#10]
Maybe that's deliberate, but as someone who one speaks one language it's not very useful.

I eventually hacked the lisp and python files to get it back to English.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/mind-wave/commit/f23965a2848a30e98462e895cb0f3997dfce84f4 fix this issue.

**Comment by AddyLaddy** [comment]
Great thanks for the quick fix! I still see one function you didn't change 
```
(defun mind-wave-chat-continue ()
  (interactive)
  (mind-wave-chat-ask-with-message "继续"))

**Comment by AddyLaddy** [comment]
I also had to patch it further with 
```
diff --git a/mind-wave.el b/mind-wave.el
index 64001f4..f49d075 100644
--- a/mind-wave.el
+++ b/mind-wave.el
@@ -88,12 +88,15 @@
   :type 'boolean
   :group 'mind-wave)
 
+(defun file-name-concat (&rest parts)
+  (reduce (lambda (a b) (expand-file-name b a)) parts))
+
 (defcustom mind-wave-api-key-path (expand-file-name (file-name-concat user-emacs-directory "mind-wave" "chatgpt_api_key.txt"))
   "The path to store OpenAI API Key."
   :type 'boolean
   :group 'mind-wave)
 
-(defvar mind-wave-lang (car (string-split (getenv "LANG") "\\.")))
+(defvar mind-wave-lang (car (split-string (getenv "LANG") "\\.")))
 
 (defvar mind-wave-server nil
   "The Mind-Wave Server.")
```

**Comment by manateelazycat** [comment]
Done, thanks for patch.

**Comment by Ethanlinyf** [comment]
It is recommended to modify the "reduce" function to "cl-reduce" from the "cl-lib" library in order to avoid encountering the error message, "Symbol's function definition is void: reduce".
