### ISSUE TITLE
提供自定义储存路径

### ISSUE THREAD

**Issue by randomwangran** [manateelazycat/mind-wave#13]
Instead of `set-visited-file-name`, possilbe `/usr/define/location/as/prefix/`?

https://github.com/manateelazycat/mind-wave/blob/f9a2689846c925cdfbcbef8eecf1e9dab65a4d77/mind-wave.el#L420-L426

**Comment by manateelazycat** [comment]
这个文件名，本来就是你自己任意路径打开的chat文件名

为什么这地方还要提供自定义呢？
