### ISSUE TITLE
提供一个更好的输出选项？

### ISSUE THREAD

**Issue by randomwangran** [manateelazycat/mind-wave#15]
目前 在我有限的了解下， MineWave 中许多函数的返回内容，很多时候都是返
回到一个独立的 buffer 内容下。 能不能提供一个选项， 这样可以使我在任何
地方都可以调用这个函数， 它的返回值指向一个比如说，Temp Buffer, 然后
这个 Temp Buffer 内容可以被Postframe去读取 展示在当前的buffer下 这样的
话根据不同的场景用户可以选择插入, 改写,或者关闭,从而不打乱整体的frame
window布局？

**Comment by manateelazycat** [comment]
这样并不好用，因为有时候重构代码，你不可能整体替换的

分屏的窗口的话，更容易操作

可以增加一个恢复上一次窗口布局的函数

**Comment by manateelazycat** [comment]
请参考补丁 https://github.com/manateelazycat/mind-wave/commit/c09ef5633d9b838eef60804c3d4bcca8433e75af
