### ISSUE TITLE
无环境变量 `LANG` 时报错(wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by douo** [manateelazycat/mind-wave#16]
报错信息如下：
文档并没有声明要设置  LANG 环境变量。
```
  split-string(nil "\\.")
  (car (split-string (getenv "LANG") "\\."))
  (defvar mind-wave-lang (car (split-string (getenv "LANG") "\\.")))
```

https://github.com/manateelazycat/mind-wave/blame/c69b71308a246a26f8282359cb55bf9ce321c5a5/mind-wave.el#L125

**Comment by manateelazycat** [comment]
已经修复了 https://github.com/manateelazycat/mind-wave/commit/0dddcbb52b141786fbe150e7855050cf1dae3c2e
