### ISSUE TITLE
[Proposal] remove ---- xxx ---- markers, user markdown headlines in chat mode

### ISSUE THREAD

**Issue by thanhvg** [manateelazycat/mind-wave#26]
Replace usages of:

-  `"------ User ------\n"` marker with `# > User:`
-  `"------ Assistant ------\n"` with `## > Assistant:`

Example:

``` md
# > User: hello

## > Assistant: Hello! How can I assist you today?

```

Benefit:
- nice presentation, similar to markdown 
- built in support for imenu, 
- can hide and show chat nodes

I have a prototype here https://github.com/thanhvg/mind-wave/commit/4995c7f23251139ad891c5640af78a7bd63945d2 if you think it's a good idea I can create a PR.

Thanks.

**Comment by manateelazycat** [comment]
It's not a good idea.

Sometimes, we want ChatGPT convert Markdown documentation or output as Markdown syntax.

If we use # as headline, mind-wave parser program will confused if ChatGPT anwser include # too.

Anyway, thanks for your kind suggestion.

**Comment by thanhvg** [comment]
But the proposed markers (`## > ` and `# > `) are chosen so that the  chance they are at the start of the lines are very small.  Or we can find better markers. My point is that chat mode should take advantage of markdown headline feature.

**Comment by manateelazycat** [comment]
you can try send a PR
