### ISSUE TITLE
Is it possible to get API key from environment variable?

### ISSUE THREAD

**Issue by ezchi** [manateelazycat/mind-wave#3]
Playing around several tools and applications based on ChatGPT. Some of them get the API key through environment `OPENAI_API_KEY`. Do you think that will be better than source it from API txt file?

    export OPENAI_API_KEY='your_api_key'

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/mind-wave/commit/e2403ac0bbc9a54aaff647e65a9ec7c17d615683
