### ISSUE TITLE
SSL模块问题

### ISSUE THREAD

**Issue by xingforce** [manateelazycat/mind-wave#35]
urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168

这个怎么办？谢谢~

**Comment by manateelazycat** [comment]
这个一般都是你发行版打包的问题， 换用 arch linux 吧， mind-wave 爱莫能助。
