### ISSUE TITLE
[feature request] system prompt

### ISSUE THREAD

**Issue by lemyx** [manateelazycat/mind-wave#38]
猫大，很喜欢mind-wave，在**网络顺畅**的时候很好用。

有些 ChatGPT 的应用，主打对话，会针对不同场景做 system prompt。

为 mind-wave 引入 system prompt 的一种方式是 （与其他 app 的思路相同）：
设计不同场景下的 *.chat 文件，在最开头写入这种场景的 system prompt 【下图为一个典型例子】
![image](https://github.com/manateelazycat/mind-wave/assets/119666897/aecf9562-67a4-4ed4-9d49-86b689978612)

但应该还有其他解决思路，请问猫大是否觉得 system prompt 的引入会帮助 mind-wave 性能的提升？比如在文档模式、摘要模式、代码模式等等。

**Comment by manateelazycat** [comment]
mind-wave 其实有角色扮演的代码， 比如 https://github.com/manateelazycat/mind-wave/blob/b787803ff745dde28727c10833b397d846fc1f7f/mind-wave.el#L126 这些 -role 结尾的选项。

mind-wave 目前是直接把 role 植入特定的命令中， 你可以根据这些 role 的方式来写自定义函数， 比如 https://github.com/manateelazycat/mind-wave/blob/b787803ff745dde28727c10833b397d846fc1f7f/mind-wave.el#L781

我个人认为 role 的作用在于对结果有特定需求的 ‘微调’， 比如希望输出的文字按某种主观的风格输出。

但是我认为 role 对于 chat-gpt 的性能没啥影响的， 这个通用人工智能如果只是解决问题， 甚至有时候都不需要设定 role。
