### ISSUE TITLE
mind-wave-explain-code 返回解析结果时 文字的顺序与人的正常思维相反

### ISSUE THREAD

**Issue by randomwangran** [manateelazycat/mind-wave#4]
目前是白洞效果

https://user-images.githubusercontent.com/8197831/224572061-874ee4b9-ebb3-4c48-a6ff-041c76177237.mp4

**Comment by manateelazycat** [comment]
emacs -Q 对比测试

**Comment by manateelazycat** [comment]
更新最新版， 已经修复了。
