### ISSUE TITLE
从 elisp 提供 API KEY

### ISSUE THREAD

**Issue by randomwangran** [manateelazycat/mind-wave#5]
从 elisp 提供 api key, 类似：

`(setq mind-wave-api-key "sk-xxxx")`

虽有

https://github.com/manateelazycat/mind-wave/blob/7996e649d43d7ba12c552fcc8a5048af5eb8fe08/mind_wave.py#L59

增加易用性

**Comment by manateelazycat** [comment]
这样会有泄露API key的风险。
